package com.dectechsolutions.instinct;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4.
 * 2015-11-25T12:30:55.955+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://dectechsolutions.com/Instinct", name = "InstinctActionWebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface InstinctActionWebServiceSoap 
{

    @WebMethod(operationName = "InstinctActionStringReturn", action = "http://dectechsolutions.com/Instinct/InstinctActionStringReturn")
    @Action(input = "http://dectechsolutions.com/Instinct/InstinctActionStringReturn", output = "http://dectechsolutions.com/Instinct/InstinctActionWebServiceSoap/InstinctActionStringReturnResponse")
    @RequestWrapper(localName = "InstinctActionStringReturn", targetNamespace = "http://dectechsolutions.com/Instinct", className = "com.dectechsolutions.instinct.InstinctActionStringReturn")
    @ResponseWrapper(localName = "InstinctActionStringReturnResponse", targetNamespace = "http://dectechsolutions.com/Instinct", className = "com.dectechsolutions.instinct.InstinctActionStringReturnResponse")
    @WebResult(name = "InstinctActionStringReturnResult", targetNamespace = "http://dectechsolutions.com/Instinct")
    java.lang.String instinctActionStringReturn(
        @WebParam(name = "actionString", targetNamespace = "http://dectechsolutions.com/Instinct")
        java.lang.String actionString
    );

    @WebMethod(operationName = "InstinctActionXMLStringReturn", action = "http://dectechsolutions.com/Instinct/InstinctActionXMLStringReturn")
    @Action(input = "http://dectechsolutions.com/Instinct/InstinctActionXMLStringReturn", output = "http://dectechsolutions.com/Instinct/InstinctActionWebServiceSoap/InstinctActionXMLStringReturnResponse")
    @RequestWrapper(localName = "InstinctActionXMLStringReturn", targetNamespace = "http://dectechsolutions.com/Instinct", className = "com.dectechsolutions.instinct.InstinctActionXMLStringReturn")
    @ResponseWrapper(localName = "InstinctActionXMLStringReturnResponse", targetNamespace = "http://dectechsolutions.com/Instinct", className = "com.dectechsolutions.instinct.InstinctActionXMLStringReturnResponse")
    @WebResult(name = "InstinctActionXMLStringReturnResult", targetNamespace = "http://dectechsolutions.com/Instinct")
    java.lang.String instinctActionXMLStringReturn(
        @WebParam(name = "actionString", targetNamespace = "http://dectechsolutions.com/Instinct")
        java.lang.String actionString
    );
}
